### PR TITLE
In UM2N Dockerfile use firedrake-parmmg as base

### PR DESCRIPTION
**Pull request by ddundo**
Related to #13. Cuts down the size of UM2N Docker image by about 4GB.

### CODE REVIEW

**Review by jwallwork23 — COMMENTED** [review]
I'm surprised this would cut down the size... I would've expected it to be bigger, given that `firedrake-parmmg` surely has more stuff in it than `firedrake-vanilla`?

**Comment by ddundo** [comment]
They merged my changes (https://github.com/firedrakeproject/firedrake/pull/3916) and `firedrake-vanilla` is now 5.6GB, compared to `firedrake-parmmg`'s 5GB. Feel free to close this PR if you'd prefer to stick with `firedrake-vanilla` :)

**Comment by jwallwork23** [comment]
> They merged my changes ([firedrakeproject/firedrake#3916](https://github.com/firedrakeproject/firedrake/pull/3916)) and `firedrake-vanilla` is now 5.6GB, compared to `firedrake-parmmg`'s 5GB. Feel free to close this PR if you'd prefer to stick with `firedrake-vanilla` :)

Nice - congrats! So `firedrake-vanilla` is still larger because it has separate Dockerfiles for the env, PETSc, and Firedrake?

**Comment by ddundo** [comment]
> Nice - congrats! So `firedrake-vanilla` is still larger because it has separate Dockerfiles for the env, PETSc, and Firedrake?

Thanks! Their firedrake-env image is like our former petsc-parmmg image, which in their case is 0.8GB larger (3.6GB to our 2.8GB). I don't exactly know what all they install there, but seems like quite a bit more

**Review by jwallwork23 — APPROVED** [review]
Let's keep it in-house then! Happy for this to go in, thanks @ddundo.

**Pull request merged**
